[project]
name = "kmxwasm-semantics"
version = "0.1.0"
source = "."

[dependencies]
elrond-semantics={ path = "elrond-semantics" }

[targets.llvm]
main-file = 'elrond-wasm.md'
backend='llvm'

[targets.haskell]
main-file = 'elrond-wasm.md'
backend='haskell'

[targets.lemma-proofs]
main-file = 'lemmas/semantics/elrond-wasm-lemma-proofs.md'
backend='haskell'
