[project]
name = "kmxwasm-semantics"
version = "0.1.0"
source = "."

[dependencies]
elrond-semantics={ path = "mx-semantics" }

[targets.llvm]
main-file = 'mx-wasm.md'
backend='llvm'

[targets.haskell]
main-file = 'mx-wasm.md'
backend='haskell'

[targets.lemma-proofs]
main-file = 'lemmas/semantics/mx-wasm-lemma-proofs.md'
backend='haskell'

[targets.llvm-library]
llvm-kompile-type='c'
main-file = 'mx-wasm.md'
backend='llvm'
