name: 'Test'
on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-code-quality-checks:
    name: 'Code Quality Checks'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
          submodules: recursive
      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v8
      - name: 'Build and run code quality checks'
        run: make -C kmxwasm check
  unit-tests:
    name: 'Kmxwasm unittests'
    runs-on: [self-hosted, linux, normal]
    needs: [python-code-quality-checks]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
          submodules: recursive
      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          container-name: mx-wasm-ci-${{ github.sha }}
      - name: 'Install dependencies'
        run: docker exec --user user mx-wasm-ci-${GITHUB_SHA} poetry -C kmxwasm install
      - name: 'Run unit tests'
        run: docker exec --user user mx-wasm-ci-${GITHUB_SHA} make -C kmxwasm test-unit
      - name: 'Tear down Docker'
        if: always()
        run: docker stop --time 0 mx-wasm-ci-${GITHUB_SHA}
  integration-tests:
    name: 'Kmxwasm integration tests'
    runs-on: [self-hosted, linux, normal]
    needs: [python-code-quality-checks,unit-tests]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
          submodules: recursive
      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          container-name: mx-wasm-ci-${{ github.sha }}
      - name: 'Install dependencies'
        run: docker exec --user user mx-wasm-ci-${GITHUB_SHA} poetry -C kmxwasm install
      - name: 'Build Haskell semantics'
        run: docker exec --user user mx-wasm-ci-${GITHUB_SHA} make -C kmxwasm kbuild-haskell
      - name: 'Run integration tests'
        run: docker exec --user user mx-wasm-ci-${GITHUB_SHA} make -C kmxwasm test-integration
      - name: 'Tear down Docker'
        if: always()
        run: docker stop --time 0 mx-wasm-ci-${GITHUB_SHA}
  lemma-tests:
    name: 'Build and Test lemmas'
    runs-on: [self-hosted, linux, normal]
    needs: [python-code-quality-checks,unit-tests]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
          submodules: recursive
      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          container-name: mx-wasm-ci-${{ github.sha }}
      - name: 'Install dependencies'
        run: docker exec --user user mx-wasm-ci-${GITHUB_SHA} poetry -C kmxwasm install
      - name: 'Check lemmas are up to date'
        run: docker exec --user user mx-wasm-ci-${GITHUB_SHA} make -C kmxwasm test-lemmas-not-changed
      - name: 'Test lemmas'
        run: docker exec --user user mx-wasm-ci-${GITHUB_SHA} make -C kmxwasm test-lemmas-unit
      - name: 'Prove lemmas'
        run: docker exec --user user mx-wasm-ci-${GITHUB_SHA} make -C kmxwasm test-proofs
      - name: 'Tear down Docker'
        if: always()
        run: docker stop --time 0 mx-wasm-ci-${GITHUB_SHA}
