name: 'Update Version'
on:
  push:
    branches:
      - '_update-deps/runtimeverification/mx-semantics'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  update-versions:
    name: 'Update pyk version'
    runs-on: [self-hosted, linux, flyweight]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
      - name: 'Configure GitHub user'
        run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v8
      - name: 'Update mx-semantics'
        run: |
          KMULTIVERSX_VERSION=$(cat deps/mx-semantics_release)
          cd deps/mx-semantics
          git fetch --tags
          git checkout v${KMULTIVERSX_VERSION}
          cd ../..
          git add deps/mx-semantics && git commit -m "deps/mx-semantics: update submodule v${KMULTIVERSX_VERSION}" || true
      - name: 'Update poetry files'
        run: |
          KMULTIVERSX_VERSION=$(cat deps/mx-semantics_release)
          sed -i 's!kmultiversx = { git = "https://github.com/runtimeverification/mx-semantics.git", tag = "[v0-9\.]*", subdirectory = "kmultiversx" }!kmultiversx = { git = "https://github.com/runtimeverification/mx-semantics.git", tag = "v'${KMULTIVERSX_VERSION}'", subdirectory = "kmultiversx" }!' kmxwasm/pyproject.toml
          poetry -C kmxwasm update
          git add kmxwasm/pyproject.toml kmxwasm/poetry.lock && git commit -m 'kmxwasm/{pyproject.toml,poetry.lock}: sync Poetry files' || true
      - name: 'Update K release'
        run: |
          K_VERSION=$(poetry -C kmxwasm run python3 -c 'import pyk; print(pyk.__version__)')
          echo ${K_VERSION} > deps/k_release
          git add deps/k_release && git commit -m "deps/k_release: sync release file version ${K_VERSION}" || true
      - name: 'Update Nix flake inputs'
        run: |
          K_VERSION=$(cat deps/k_release)
          sed -i 's!    k-framework.url = "github:runtimeverification/k/[v0-9\.]*"!    k-framework.url = "github:runtimeverification/k/v'"${K_VERSION}"'"!' flake.nix
          nix --extra-experimental-features 'nix-command flakes' --show-trace flake update
          git add flake.nix flake.lock && git commit -m 'flake.{nix,lock}: update Nix derivations' || true
      - name: 'Push updates'
        run: git push
