name: 'Update Version'
on:
  push:
    branches:
      - '_update-deps/runtimeverification/mx-semantics'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  update-versions:
    name: 'Update pyk version'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.JENKINS_GITHUB_PAT }}

      - name: 'Configure GitHub user'
        run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com

      - name: 'Install Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v8
      - name: 'Update poetry files'
        run: |
          KMULTIVERSX_VERSION=$(cat deps/mx-semantics_release)
          sed -i 's!kmultiversx = { git = "https://github.com/runtimeverification/mx-semantics.git", tag = "[v0-9\.]*", subdirectory = "kmultiversx" }!kmultiversx = { git = "https://github.com/runtimeverification/mx-semantics.git", tag = "v'${KMULTIVERSX_VERSION}'", subdirectory = "kmultiversx" }!' kmxwasm/pyproject.toml
          poetry -C kmxwasm update
          git add kmxwasm/pyproject.toml kmxwasm/poetry.lock && git commit -m 'kmxwasm/{pyproject.toml,poetry.lock}: sync Poetry files' || true

      - name: 'Update K release'
        run: |
          K_VERSION=$(poetry -C kmxwasm run python3 -c 'import pyk; print(pyk.__version__)')
          echo ${K_VERSION} > deps/k_release
          git add deps/k_release && git commit -m "deps/k_release: sync release file version ${K_VERSION}" || true

      - name: 'Install Nix/Cachix'
        uses: cachix/install-nix-action@v19
        with:
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: k-framework
          authToken: ${{ secrets.CACHIX_PUBLIC_TOKEN }}

      - name: 'Update Nix flake inputs'
        run: |
          KMULTIVERSX_VERSION=$(cat deps/mx-semantics_release)

          sed -i 's!    mx-semantics.url = "github:runtimeverification/mx-semantics/[v0-9\.]*"!    mx-semantics.url = "github:runtimeverification/mx-semantics/v'"${KMULTIVERSX_VERSION}"'"!' flake.nix

          nix --extra-experimental-features 'nix-command flakes' --show-trace flake update
          git add flake.nix flake.lock && git commit -m 'flake.{nix,lock}: update Nix derivations' || true

      - name: 'Push updates'
        run: git push
